# Generated by Django 5.1.2 on 2024-11-21 12:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_blog', '0003_alter_category_options_alter_tutorial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='teacher_blog.category', verbose_name='Батьківська категорія'),
        ),
        migrations.AlterField(
            model_name='category',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=127, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to='teacher_blog.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=127, verbose_name='Назва'),
        ),
    ]
