# Generated by Django 5.1.2 on 2024-11-21 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_blog', '0004_alter_category_parent_alter_category_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Текст'),
        ),
    ]
